import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import * as crypto from 'node:crypto';
const api={};const workflows={createProductsWorkflow:scope=>({run:input=>scope.resolve('create')(input)})};
new Function('require','exports',ts.transpileModule(fs.readFileSync('server-module/src/lib/cms-sealed-finder.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>name==='node:crypto'?crypto:name==='@medusajs/framework/utils'?{Modules:{PRODUCT:'product',FILE:'file',LOCKING:'lock',SALES_CHANNEL:'channel',FULFILLMENT:'profile'}}:workflows,api);
function fixture(){const data=[];function ref(value){const i=data.length;data.push(null);data[i]=Array.isArray(value)?value.map(ref):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,ref(v)])):value;return i;}ref({setAbbreviation:'SOS',name:'Secrets of Strixhaven',products:[{sys:{id:'one'},fields:{name:'Play Booster Display',sku:'SKU',images:[{fields:{title:'Box image',file:{url:'//images.ctfassets.net/space/box.png'}}}]}}]});return `<script id="__NUXT_DATA__">${JSON.stringify(data)}</script>`;}
test('official preview extracts products, groups and image URLs without executing page scripts',()=>{const result=api.parseWpn(fixture(),'sos');assert.equal(result.products.length,1);assert.equal(result.products[0].category,'booster-boxes');assert.equal(result.products[0].images[0],'https://images.ctfassets.net/space/box.png');assert.equal(result.assets.length,1);assert.throws(()=>api.parseWpn(fixture(),'ltr'),/does not match/);});
test('asset sources reject private, unexpected and credential-bearing URLs',()=>{for(const u of ['http://localhost/file','https://127.0.0.1/a','https://images.ctfassets.net.evil.test/a','https://x:pass@images.ctfassets.net/a'])assert.throws(()=>api.trustedAsset(u));});
test('preview approval verifies signature and expiry',()=>{const old=process.env.JWT_SECRET;process.env.JWT_SECRET='test-signing-key';try{const p={code:'sos',expires:Date.now()+10000,products:[],assets:[]};const token=api.signPreview(p);assert.equal(api.verifyPreview(token).code,'sos');assert.throws(()=>api.verifyPreview(token.slice(0,-8)+'abcdefgh'));assert.throws(()=>api.verifyPreview(api.signPreview({...p,expires:0})),/expired/);}finally{if(old===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=old;}});
test('preview and acceptance reject unapproved selections before storage or product writes',async()=>{const old=process.env.JWT_SECRET,driver=process.env.FILE_STORAGE_DRIVER;process.env.JWT_SECRET='test';process.env.FILE_STORAGE_DRIVER='s3';const response=()=>({status(n){this.code=n;return this;},json(b){this.body=b;}});try{const req={scope:{resolve:()=>({})}};const res=response();await api.sealedFinder(req,res,{action:'sealed_find',game:'other',code:'sos'});assert.equal(res.code,400);const token=api.signPreview({expires:Date.now()+10000,products:[],assets:[]});const rejected=response();await api.sealedFinder(req,rejected,{action:'sealed_accept',token,products:['injected']});assert.equal(rejected.code,400);assert.match(rejected.body.message,/Selection/);}finally{if(old===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=old;if(driver===undefined)delete process.env.FILE_STORAGE_DRIVER;else process.env.FILE_STORAGE_DRIVER=driver;}});
test('duplicate detection handles uppercase legacy set codes without conflating shared pack/display SKUs',()=>{const existing={title:'Secrets of Strixhaven Play Booster',metadata:{set_code:'SOS',source_sku:'same'}};assert.equal(api.matchesFoundProduct(existing,{id:'x',name:'Play Booster',sku:'same'},'Secrets of Strixhaven','sos'),true);assert.equal(api.matchesFoundProduct(existing,{id:'y',name:'Play Booster Display',sku:'same'},'Secrets of Strixhaven','sos'),false);});
test('acceptance stores only approved assets in separate prefixes and creates zero-stock drafts; retries reuse them',async()=>{
 const oldKey=process.env.JWT_SECRET,oldDriver=process.env.FILE_STORAGE_DRIVER,oldFetch=global.fetch;process.env.JWT_SECRET='test';process.env.FILE_STORAGE_DRIVER='s3';
 const uploads=[],products=[];let metadata={isVisible:false};
 const services={product:{listProducts:async()=>products,listProductCategories:async({handle})=>[{id:handle}]},file:{createFiles:async input=>{uploads.push(input);return {id:String(uploads.length),url:'http://storage.test/'+input.filename};}},lock:{execute:async(_,fn)=>fn()},channel:{listSalesChannels:async()=>[{id:'channel'}]},profile:{listShippingProfiles:async()=>[{id:'profile'}]},tcgCatalog:{retrieveCardSet:async()=>({id:'set',metadata}),updateCardSets:async input=>{metadata=input.metadata;}},create:async({input})=>{products.push(...input.products);return {result:[]};}};
 const preview={game:'magic-the-gathering',code:'sos',setId:'set',name:'Secrets of Strixhaven',source:'https://wpn.wizards.com/en/products/secrets-of-strixhaven',expires:Date.now()+10000,products:[{id:'p',name:'Bundle',sku:'',category:'bundles',price_clp:6291,msrp_usd:6.99,price_rate:900,images:['https://images.ctfassets.net/product.png']}],assets:[{id:'a',title:'Banner',url:'https://images.ctfassets.net/banner.png',kind:'image'},{id:'unselected',title:'Other',url:'https://images.ctfassets.net/other.png',kind:'image'}]};
 const response=()=>({status(n){this.code=n;return this;},json(b){this.body=b;}});
 try{global.fetch=async()=>new Response(new Uint8Array([137,80,78,71]),{headers:{'content-type':'image/png'}});const body={action:'sealed_accept',token:api.signPreview(preview),products:['p'],assets:['a']};const req={scope:{resolve:name=>services[name]}};const res=response();await api.sealedFinder(req,res,body);assert.equal(res.body.results.length,2);assert.equal(products[0].status,'draft');assert.deepEqual(products[0].variants[0].prices,[{currency_code:'clp',amount:6291}]);assert.equal(products[0].metadata.price_estimate.usd,6.99);assert.ok(uploads[0].filename.includes('/products/'));assert.ok(uploads[1].filename.includes('/graphics/'));assert.equal(uploads.length,2);assert.equal(metadata.isVisible,false);await api.sealedFinder(req,response(),body);assert.equal(products.length,1);assert.equal(uploads.length,2);}finally{global.fetch=oldFetch;if(oldKey===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=oldKey;if(oldDriver===undefined)delete process.env.FILE_STORAGE_DRIVER;else process.env.FILE_STORAGE_DRIVER=oldDriver;}
});
test('banner selection validates stored graphics and preserves set and product metadata',async()=>{
 let metadata={isVisible:false,sealed_assets:[{id:'header',folder:'graphics',url:'http://storage.test/header.png'},{id:'zip',folder:'graphics',url:'http://storage.test/archive.zip'}]};
 const products=[{id:'sealed',metadata:{kind:'sealed',set_code:'TMT',custom:true}},{id:'single',metadata:{kind:'single',set_code:'TMT'}}];
 const services={tcgCatalog:{listCardSets:async()=>[{id:'set',metadata}],retrieveCardSet:async()=>({id:'set',metadata}),updateCardSets:async s=>{metadata=s.metadata;}},product:{listProducts:async()=>products,retrieveProduct:async id=>products.find(p=>p.id===id),updateProducts:async(id,data)=>Object.assign(products.find(p=>p.id===id),data)},lock:{execute:async(_,fn)=>fn()}};
 const req={scope:{resolve:n=>services[n]}};const response=()=>({status(n){this.code=n;return this;},json(b){this.body=b;}});
 for(const asset_id of ['zip','unknown']){const r=response();await api.sealedFinder(req,r,{action:'sealed_banner',code:'TMT',asset_id});assert.equal(r.code,400);}
 const r=response();await api.sealedFinder(req,r,{action:'sealed_banner',code:'TMT',asset_id:'header'});assert.equal(r.body.banner,'http://storage.test/header.png');assert.equal(products[0].metadata.custom,true);assert.equal(products[0].metadata.banner_image,r.body.banner);assert.equal(products[1].metadata.banner_image,undefined);assert.equal(metadata.isVisible,false);assert.equal(metadata.sealed_banner_url,r.body.banner);
});
test('finder converts official MSRP into CLP and tolerates unavailable exchange rates',async()=>{
 const oldFetch=global.fetch,oldKey=process.env.JWT_SECRET;process.env.JWT_SECRET='test';
 const html=fixture().replace('"sku":','"msrp":');
 const req={scope:{resolve:n=>n==='tcgCatalog'?{listCardSets:async()=>[{id:'set',name:'SOS'}]}:{listProducts:async()=>[]}}};
 const response=()=>({status(n){this.code=n;return this;},json(b){this.body=b;}});
 try{
   global.fetch=async url=>String(url).includes('mindicador')?new Response(JSON.stringify({serie:[{valor:900,fecha:new Date().toISOString()}]})):new Response(html.replace('"SKU"','"$6.99"'));
   const r=response();await api.sealedFinder(req,r,{action:'sealed_find',game:'magic-the-gathering',code:'sos'});assert.equal(r.body.products[0].price_clp,6291);assert.equal(api.verifyPreview(r.body.token).products[0].price_clp,6291);
   global.fetch=async url=>{if(String(url).includes('mindicador'))throw new Error('offline');return new Response(html.replace('"SKU"','"$6.99"'));};
   const fallback=response();await api.sealedFinder(req,fallback,{action:'sealed_find',game:'magic-the-gathering',code:'sos'});assert.equal(fallback.body.products[0].price_clp,undefined);assert.match(fallback.body.priceWarning,/unavailable/);
 }finally{global.fetch=oldFetch;if(oldKey===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=oldKey;}
});
