import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const exports={};
const flowNames=['createProductsWorkflow','updateProductsWorkflow','updateProductVariantsWorkflow','createInventoryLevelsWorkflow','linkSalesChannelsToStockLocationWorkflow'];
const deps={'node:crypto':{randomUUID:()=> 'test-unique-id'},'@medusajs/framework/utils':{Modules:{PRODUCT:'product',LOCKING:'locking',INVENTORY:'inventory',STOCK_LOCATION:'location',SALES_CHANNEL:'channel',FULFILLMENT:'fulfillment'},ContainerRegistrationKeys:{QUERY:'query'}},'@medusajs/medusa/core-flows':Object.fromEntries(flowNames.map(name=>[name,scope=>({run:args=>scope.resolve('flows')[name](args)})]))};
new Function('require','exports',ts.transpileModule(fs.readFileSync('server-module/src/lib/cms-sealed.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>deps[name],exports);
const categories=[{id:'root',handle:'sealed-products',name:'Sealed'},{id:'boxes',handle:'sealed-booster-boxes',name:'Boxes',parent_category_id:'root'},{id:'nested',handle:'nested',parent_category_id:'boxes'},{id:'singles',handle:'singles'}];
function scenario(){
 const calls=[];const product={id:'p',title:'Box',metadata:{source_url:'keep',demo_inventory:true},categories:[categories[1]],variants:[{id:'v'}]};
 const variant={id:'v',manage_inventory:true,inventory_items:[{inventory_item_id:'item',required_quantity:1}],price_set:{prices:[{id:'clp',currency_code:'clp',amount:500},{id:'usd',currency_code:'usd',amount:10}]}};
 const service={listProductCategories:async()=>categories,retrieveProduct:async()=>product,listAndCountProducts:async filters=>{calls.push(['filter',filters]);return [[product],1];}};
 const services={product:service,locking:{execute:async(key,fn)=>{calls.push(['lock',key]);return fn();}},location:{retrieveStockLocation:async()=>({id:'loc'})},channel:{listSalesChannels:async()=>[{id:'channel'}]},fulfillment:{listShippingProfiles:async()=>[{id:'profile'}]},inventory:{listInventoryLevels:async()=>[{available_quantity:3,reserved_quantity:2,location_id:'loc'}],adjustInventory:async(...args)=>calls.push(['adjust',args])},query:{graph:async({entity})=>({data:entity==='product'?[{sales_channels:[{id:'channel'}]}]:[variant]})},flows:Object.fromEntries(flowNames.map(name=>[name,async args=>{calls.push([name,args]);return {result:[]};}]))};
 const req={scope:{resolve:name=>services[name]},query:{}};const res={code:200,status(n){this.code=n;return this;},json(body){this.body=body;return this;}};
 return {req,res,services,calls,product,variant};
}
test('sealed category membership follows existing tree without including singles',()=>assert.deepEqual([...exports.sealedCategoryIds(categories)],['root','boxes','nested']));
test('sealed listing limits categories and projects inventory and CLP price',async()=>{const s=scenario();await exports.getSealed(s.req,s.res);assert.equal(s.res.body.rows[0].variants[0].price_clp,500);assert.equal(s.res.body.rows[0].variants[0].levels[0].reserved_quantity,2);assert.deepEqual(s.calls[0][1].categories.id,['root','boxes','nested']);});
test('sealed mutations reject products outside sealed groups and foreign variants',async()=>{const s=scenario();s.product.categories=[categories[3]];await exports.postSealed(s.req,s.res,{action:'sealed_price',product_id:'p',variant_id:'v',price_clp:100});assert.equal(s.res.code,400);s.product.categories=[categories[1]];await exports.postSealed(s.req,s.res,{action:'sealed_price',product_id:'p',variant_id:'wrong',price_clp:100});assert.match(s.res.body.message,/does not belong/);assert.ok(!s.calls.some(c=>c[0]==='updateProductVariantsWorkflow'));});
test('stock subtraction protects reservations and locks same inventory item as card controls',async()=>{const s=scenario();await exports.postSealed(s.req,s.res,{action:'sealed_stock',product_id:'p',variant_id:'v',location_id:'loc',quantity:-4});assert.equal(s.res.code,400);assert.ok(!s.calls.some(c=>c[0]==='adjust'));await exports.postSealed(s.req,s.res,{action:'sealed_stock',product_id:'p',variant_id:'v',location_id:'loc',quantity:-2});assert.deepEqual(s.calls.find(c=>c[0]==='adjust')[1],['item','loc',-2]);assert.ok(s.calls.some(c=>c[1]==='cms-inventory:item'));});
test('sealed price update preserves other currencies',async()=>{const s=scenario();await exports.postSealed(s.req,s.res,{action:'sealed_price',product_id:'p',variant_id:'v',price_clp:700});const prices=s.calls.find(c=>c[0]==='updateProductVariantsWorkflow')[1].input.product_variants[0].prices;assert.equal(prices[0].amount,700);assert.equal(prices[1].amount,10);});
test('sealed product editing preserves source metadata and does not alter inventory',async()=>{const s=scenario();await exports.postSealed(s.req,s.res,{action:'sealed_save',product_id:'p',title:'Updated',status:'draft',category_id:'boxes',set:'Set',set_code:'ABC',language:'English'});assert.equal(s.res.body.ok,true);const p=s.calls.find(c=>c[0]==='updateProductsWorkflow')[1].input.products[0];assert.equal(p.metadata.source_url,'keep');assert.deepEqual(p.category_ids,['root','boxes']);assert.ok(!s.calls.some(c=>c[0]==='adjust'));});
test('new sealed product uses existing category and creates managed stock with CLP price',async()=>{const s=scenario();await exports.postSealed(s.req,s.res,{action:'sealed_create',title:'New box',category_id:'boxes',status:'draft',price_clp:10000,language:'Spanish'});assert.equal(s.res.code,201);const p=s.calls.find(c=>c[0]==='createProductsWorkflow')[1].input.products[0];assert.equal(p.metadata.kind,'sealed');assert.equal(p.variants[0].manage_inventory,true);assert.equal(p.variants[0].options.Language,'Spanish');assert.deepEqual(p.category_ids,['root','boxes']);});
test('changing sealed image updates storefront metadata overrides as well as thumbnail',async()=>{const s=scenario();s.product.thumbnail='https://old.test/image.jpg';s.product.metadata.product_cutout=s.product.thumbnail;await exports.postSealed(s.req,s.res,{action:'sealed_save',product_id:'p',title:'Box',status:'draft',category_id:'boxes',thumbnail:'http://localhost:9002/banned-cards/box.jpg'});const p=s.calls.find(c=>c[0]==='updateProductsWorkflow')[1].input.products[0];assert.equal(p.metadata.product_cutout,p.thumbnail);assert.equal(p.metadata.image_url,p.thumbnail);});
test('row status updates without changing stock and blocks publishing unpriced products',async()=>{const s=scenario();await exports.postSealed(s.req,s.res,{action:'sealed_status',product_id:'p',status:'draft'});assert.equal(s.res.body.ok,true);assert.equal(s.calls.find(c=>c[0]==='updateProductsWorkflow')[1].input.products[0].status,'draft');s.variant.price_set.prices=[];await exports.postSealed(s.req,s.res,{action:'sealed_status',product_id:'p',status:'published'});assert.match(s.res.body.message,/positive CLP/);});
test('stock adjustment returns refreshed levels for row-only UI updates',async()=>{const s=scenario();await exports.postSealed(s.req,s.res,{action:'sealed_stock',product_id:'p',variant_id:'v',location_id:'loc',quantity:1});assert.equal(s.res.body.ok,true);assert.equal(s.res.body.levels[0].available_quantity,3);});
